# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23ec2139f4d358ff5fdf092adca287b458be613ce790d490470b3e240a7d8d4860a3eb76355a3603a572e3957f0bd502241a40931aacdb8c72fa78cc8d656a89

test:
  secret_key_base: b2771d9d95d80fa3e8eb30571dcf190907507f2cae78cc577064bb382e7c9cdffbbca861ef1e4080b6d3f2bd77e72189dcba87d79bb3c70c7050c4d7e30b0b94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
